type IssueItem = {
  id: string;
  title: string;
  userName: string;
  userAvatar?: string;
  status: "To Do" | "In Progress" | "Review" | "Completed";
  category: "Bug" | "Feature" | "Enhancement" | "Question";
  priority: "Low" | "Medium" | "High" | "Critical";
  team: string;
  tag: string[];
};

export const dummy: IssueItem[] = [
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
  {
    id: "r68l0ujq9ib00",
    title: "Ad minim veniam, quis nostrud exercitation ullamco laboris",
    userName: "Minim",
    userAvatar: "https://robohash.org/r68l.png?set=set5&size=16x16",
    status: "Completed",
    category: "Feature",
    priority: "Low",
    team: "Flyboyz",
    tag: ["onyh", "q807"],
  },
  {
    id: "id3rzcaahn000",
    title: "Dolore magna aliqua. Ut enim ad minim veniam, quis",
    userName: "Exercitation",
    userAvatar: "https://robohash.org/id3r.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Feature",
    priority: "Low",
    team: "Netility",
    tag: ["hksy", "vf07"],
  },
  {
    id: "db3w9rvlfsw00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/db3w.png?set=set5&size=16x16",
    status: "Completed",
    category: "Enhancement",
    priority: "Medium",
    team: "Miracula",
    tag: ["d09p"],
  },
  {
    id: "3lfbddcbqnd00",
    title: "Sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
    userName: "Laboris",
    userAvatar: "https://robohash.org/3lfb.png?set=set5&size=16x16",
    status: "To Do",
    category: "Feature",
    priority: "Medium",
    team: "Olympix",
    tag: [],
  },
  {
    id: "dwa6t2rypfb00",
    title: "Incididunt ut labore et dolore magna aliqua. Ut enim",
    userName: "Ullamco",
    userAvatar: "https://robohash.org/dwa6.png?set=set5&size=16x16",
    status: "Completed",
    category: "Bug",
    priority: "High",
    team: "Ecratic",
    tag: ["djy7"],
  },
  {
    id: "ap973ue7bg000",
    title: "Do eiusmod tempor incididunt ut labore et dolore magna",
    userName: "Laboris",
    userAvatar: "https://robohash.org/ap97.png?set=set5&size=16x16",
    status: "Review",
    category: "Feature",
    priority: "Critical",
    team: "Knowlysis",
    tag: ["ajlu"],
  },
  {
    id: "xi8mna068bk00",
    title: "Quis nostrud exercitation ullamco laboris nisi ut aliquip",
    userName: "Ut",
    userAvatar: "https://robohash.org/xi8m.png?set=set5&size=16x16",
    status: "In Progress",
    category: "Question",
    priority: "Low",
    team: "Neurocell",
    tag: ["svh0", "li0u"],
  },
];
